channels:
  # Define conda channels here. 
  - conda-forge

dependencies:
  # Define conda packages here. 
  # If available, always prefer the conda version of a package, installation will be faster and more efficient.
  # https://anaconda.org/search  
  - python=3.7.5
  - nodejs=14.17.4
  - pip:
      - robotframework-browser==9.0.1
      - rpaframework==11.4.0
rccPostInstall:
  - rfbrowser init